### ISSUE TITLE
Support for older Yocto version

### ISSUE THREAD

**Issue by Spinus1** [priv-kweihmann/meta-sca#572]
Will it be possible to support older Yocto versions? In my company we're using Yocto 2.1 for legacy projects and Yocto 2.2/2.4 for projects that are still in active development phase...
Is there a specific reason why you've started from Yocto Thud? Maybe you're using poky classes/scripts that are not available in earlier Yocto releases?

Currently we're using handwritten recipes to perform static analysis with **cppcheck** and **Parasoft**, but using a layer like meta-sca will certainly improve our job...for sure if meta-sca will work in our current baseline I'll certainly able to contribute to it :)

BR,
Alessio

**Comment by priv-kweihmann** [comment]
Hi Alessio,

First of all I really appreciate your interest in this layer - and now regarding your questions:

- Parasoft is nothing that would be part of this layer by default, as it is closed source software, as far as I know (please correct if I'm mistaken about that) and I tend to keep all tools in this layer FOSS only.
Nevertheless I'm planning to document how-to add a custom tool anyway (but haven't unfortunately found the time to do so yet), so this could be easily provided by you.

- Why thud as a starting point?
  Basically when I started coding all these things here thud was the current release and neither my then employer nor I that any legacy projects to maintain - so it kind of happened coincidentally

- Now about the support for layer "down" to krogoth
  I don't see any specific reasons why it won't be possible for a very limited subset of the current layer.
  What not will be working is:
  - go support: as go came in at pyro for the first time (and there as a, now, very old version)
  - llvm support: as most of the tools using clang/llvm don't work with very old releases (< clang 7.0)
  - php support: might be tricky, as krogoth is shipping php 5.5, which isn't very well supported by the tools
  - all tools based on npm: because npm/nodejs is ancient in older yocto release and I personally don't know any tool that supports building of npm < 6.0 atm

Rest the should be working by putting in some effort. 

Long story short, there shouldn't be a technical issue, which prevents the support of older layer versions, but the time to be invested.
What I could offer would be a limited subset for following releases of YOCTO
* krogoth
* rocko
* sumo
* pyro

**What needs to be discussed is the 'subset' - so what tools/language to you __really__ need?**

From my point of view, I would setup these layers once with a fixed feature set, but there won't be much package updates form my side - but that can be easily be done by e.g. you or any other interested party by pull requests.
What those layer definitely not will get, are feature updates, as it get harder everyday to maintain support of older framework versions. 

What are your thoughts on this? 
Also could you please post a list of **must-have** modules as a comment.

THX and Regards
Konrad

**Comment by Spinus1** [comment]
Hello, thank you for the thorough answer!
In my company we're using C/C++ in majority of the cases: so it could be useful to have tools like **configcheck** (c_ppcheck,cpplint,cspell,cvecheck,flint,gcc_), plus some **bash** linter (that I've just discovered) like _bashate,stank, slick_. 
**HTML and javascript** tools could be useful as well.

But this are just the tools that could be useful in my juse case, so, maybe, these modules do not meet other people needs; furthermore I don't know the dependencies of these tools, so, maybe, they could be too hard to back port.

Regarding Parasoft, I confirm that is a proprietary tool and integrating it in meta-sca could be not so easy...in any case I can give it a try (when I can re-allocate some time from other daily businnes activities :-) )

Thanks,
Alessio

**Comment by priv-kweihmann** [comment]
@Spinus1 I just trimmed down the master so far that should work with a `krogoth` release.
Could please give it a try and report back any issues?

If `krogoth` release is working I will start using the same basis for the other YOCTO release branches.

Note: unfortunately I had to drop all support for js/html, but the rest of your suggested selection should be working - just have a look at the branch README for details.

**Comment by Spinus1** [comment]
Hello @priv-kweihmann ,
thank you for the update! Sorry but I didn't get which meta-sca branch should I use for krogoth, the **master** branch or **krogoth** branch?
I've tested both branches, but, unfortunately I get lot of errors about getVar, that should take 3 arguments (e.g: somethimes the True is missing like _getVar("STAGING_INCDIR", True)_ )

I've tried to fix them, but I've spot other issues like
` glob() got an unexpected keyword argument 'recursive'`

Probably krogoth is too old and lot of bitbake python functions have been modified since that version...I've tried it as well in rocko, but I think that it'll require some (hard?) refactoring too.

BR,
Alessio

**Comment by priv-kweihmann** [comment]
Hi,

thanks for reporting back. Regarding the branch question it would be

poky:krogoth
meta-sca:krogoth

or 

poky:master
meta-sca:master

a mix of those is currently unsupported.

`glob() got an unexpected keyword argument 'recursive'` sounds pretty familiar.
The point is that this code is actually executed by the host python.
I'm running my build machines with python 3.5, 3.6 and 3.7 - and as far as I know the `recursive`-flag was introduced in python 3.5.
That leaves me with the question on what python version is your build machine running - and maybe is updating the python version on your build machine an option (until YP 3.1 release you will need python 3.5 as a minimum anyways) - if not not just tell me your version and I try to figure out a way to fix it.

BR
Konrad

**Comment by priv-kweihmann** [comment]
I just had a look at https://www.yoctoproject.org/docs/2.1/ref-manual/ref-manual.html#required-git-tar-and-python-versions, which states that python3 isn't support at all, while https://www.yoctoproject.org/docs/2.2/ref-manual/ref-manual.html#required-git-tar-and-python-versions states it's python 3.4+.
That just emphasizes the question what python version you're using for the different builds.

**Comment by priv-kweihmann** [comment]
Nevertheless thanks for pointing out that relying on the "cloud" pipeline isn't enough (sic).
I discovered multiple bugs, while trying it out locally - so you can expect some commits the next days.
I'm still convinced that it is possible to backport stuff "down" to krogoth... (beside the python 3.4+ requirement for the host;-))

**Comment by Spinus1** [comment]
Hello,
in the build server I use to run Y2.1 builds Python 2.7.6 and Python 3.4.3 are installed: this server is running Ubuntu 14.04, so I don't think it'll be easy to upgrade to Python 3.5 - it is not available in official Ubuntu repos (furthermore we are very conservative when we have to upgrade libraries in legacy build server...to avoid any regression).

Alessio

**Comment by priv-kweihmann** [comment]
Okay, good to know. I started yesterday debugging the branch in a Debian-8 container, which should be basically the same basis you're using. Surely it will take some time, but expect it to work then;-).

I'll let you know when I'm ready

**Comment by priv-kweihmann** [comment]
Alright, that has been some tough work, but I managed to run a build for `krogoth` and `rocko` in a Ubuntu 14.04 container (the official yocto crops one).
Unfortunately I had to remove some more modules for now due to several issues, with the very old foundation code.
The branches are far from polished, but it should work for your setup.

One more thing: If you like to use modules like `configcheck`, `lynis` or `upc` you need to install `glib-2.0-dev` package to your build host (otherwise qemu-static can't be build, which is required for these tools) - so if you don't want to alter your setup, please disable those modules (see README for more details.

Please report any further issues while testing - Thanks

**Comment by priv-kweihmann** [comment]
Haven't heard back in a while.
In the meantime I release branches for 

- https://github.com/priv-kweihmann/meta-sca/releases/tag/vsumo_1.21.0
- https://github.com/priv-kweihmann/meta-sca/releases/tag/vrocko_1.21.0
- https://github.com/priv-kweihmann/meta-sca/releases/tag/vpyro_1.21.0
- https://github.com/priv-kweihmann/meta-sca/releases/tag/vkrogoth_1.21.0

so I guess it is working by now
