### ISSUE TITLE
Add a layer whitelist

### ISSUE THREAD

**Issue by gomme600** [priv-kweihmann/meta-sca#9490]
**Is your feature request related to a problem? Please describe.**

I am currently using SCA_SPARE_LAYER to blacklist layers and I would prefer to whitelist layers instead.
I don't want to inherit sca on each layer individually if possible.

**Comment by yangpeng1995** [comment]
Hi priv-kweihmann,
I recently found that the variable SCA_SPARE_LAYER is invalid when I enable SCA locally.
Then I debug found that it was caused by this submission.

I debug found that it was due to a problem with the judgment condition:
if _allow_list and x not in _allow_list:

The default variable of SCA_ALLOW_LAYER="".
So _allow_list = d.getVar("SCA_ALLOW_LAYER").split(" ")=[""].
But about judgment of "if _allow_list". In fact, "if [""]" value is true.
So this leads to always jumping out of the loop.

Can you help fix this bug?
